introduced makefiles

diff --git a/build b/build
--- a/build
+++ b/build
@@ -8,29 +8,10 @@ if [ $? -ne 0 ]; then
     echo "error: Could not access subproject folder." >&2
     exit 1
 fi
-# provide bin folder
-mkdir -p bin > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-    echo "error: Could not create bin in subproject folder." >&2
-    exit 1
-fi
-# build
-cd src > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-    echo "error: Could not access src folder." >&2
-    exit 1
-fi
-nasm -f macho main.asm
-if [ $? -ne 0 ]; then
-    echo "error: Could not build subproject." >&2
-    exit 1
-fi
-cd ..
-# - target legacy version of OS X with full 32bit support
-# - target 32bit intel architecture (i386)
-# - disable PIE 8position independent executable) as it is now deprocated
-ld -macosx_version_min 10.7.0 -arch i386 -no_pie -o bin/main src/main.o
-if [ $? -ne 0 ]; then
-    echo "error: Could not build subproject." >&2
+# build (via makefile)
+if [ -f makefile ]; then
+    make build > make.log
+else
+    echo "error: Could find makefile." >&2
     exit 1
 fi
diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -8,5 +8,10 @@ if [ $? -ne 0 ]; then
     echo "error: Could not access subproject folder." >&2
     exit 1
 fi
-# delete bin
-rm -r bin >/dev/null 2>&1
+# clean (via makefile)
+if [ -f makefile ]; then
+    make clean > make.log
+else
+    echo "error: Could find makefile." >&2
+    exit 1
+fi
diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -2,11 +2,25 @@
 
 # first argument is the name of the subproject
 subproject_name=$1
-# change directory
-cd subprojects/$subproject_name/bin > /dev/null 2>&1
+
+# build
+./build $subproject_name
+# change directory (subproject)
+cd subprojects/$subproject_name > /dev/null 2>&1
 if [ $? -ne 0 ]; then
     echo "error: Could not access subproject folder." >&2
     exit 1
 fi
-# debug
-lldb main
+# change directory (bin)
+cd bin > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "error: Could not access subproject's bin folder." >&2
+    exit 1
+fi
+# debug (via lldb)
+if [ -f main ]; then
+    lldb main
+else
+    echo "error: Could find executable." >&2
+    exit 1
+fi
