splitted up build and run script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,24 +2,22 @@
 
 # first argument is the name of the subproject
 subproject_name=$1
-echo "target subproject: $subproject_name"
 # change directory
-cd subprojects/$subproject_name
+cd subprojects/$subproject_name > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo "Could not access subproject folder." >&2
+    echo "error: Could not access subproject folder." >&2
     exit 1
 fi
 # provide bin folder
-mkdir -p bin
+mkdir -p bin > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo "Could not create bin in subproject folder." >&2
+    echo "error: Could not create bin in subproject folder." >&2
     exit 1
 fi
 # build
-echo "building ..."
-cd src
+cd src > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo "Could not access src folder." >&2
+    echo "error: Could not access src folder." >&2
     exit 1
 fi
 nasm -f macho main.asm
@@ -29,14 +27,6 @@ cd ..
 # - disable PIE 8position independent executable) as it is now deprocated
 ld -macosx_version_min 10.7.0 -arch i386 -no_pie -o bin/main src/main.o
 if [ $? -ne 0 ]; then
-    echo "Could not build subproject." >&2
-    exit 1
-fi
-# run
-echo "running ..."
-./bin/main
-ret=$?
-if [ $ret -ne 0 ]; then
-    echo "Executalbe stopped with exit code $ret." >&2
+    echo "error: Could not build subproject." >&2
     exit 1
 fi
