added build success check to scripts

diff --git a/symbol_table b/symbol_table
--- a/symbol_table
+++ b/symbol_table
@@ -5,6 +5,10 @@ subproject_name=$1
 
 # build
 ./build $subproject_name
+if [ $? -ne 0 ]; then
+    echo "error: Could not build subproject." >&2
+    exit 1
+fi
 # change directory (subproject)
 cd subprojects/$subproject_name > /dev/null 2>&1
 if [ $? -ne 0 ]; then
